modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Focamacho/SilkChest/issues"
[[mods]]
modId="silkchest"
version="${file.jarVersion}"
displayName="Silk Chest"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silk-chest"
authors="Focamacho"
description='''
Using this you can break any block using silk touch without losing the items inside it.
'''